on:
  push:
    tags-ignore:
      - '*.*'
    paths-ignore:
      - "dummy-pod-for-cd.podspec"
    branches:
      - main


jobs:
  deploy_private_pod:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: list dirs
      run: ls -l .
      
    - name: list scripts
      run: ls -l ./scripts
      
    - name: Get Previous tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: 1.0.0

    - name: bump version
      run: |
           chmod +x ./scripts/bump_version.sh
           ./scripts/bump_version.sh "${{ steps.previoustag.outputs.tag }}.$(git rev-parse --short "$GITHUB_SHA")"
    - name: tags
      run: git tag
    
    - name: recent tag
      run: git describe --tags --abbrev=0
    
    - name: commit changes
      run: |
           git config user.name "skyflow-tejesh-reddy"
           git config user.email "tejesh.skyflow@gmail.com"
           git add dummy-pod-for-cd.podspec
           git commit -m "[AUTOMATED] Private Release"

    - name: Push updated spec file
      run: |
           pod repo add private_spec
           pod repo push private_spec ./dummy-pod-for-cd.podspec
           echo "Published as Private pod
