name: Public Release

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+'


jobs:
  deploy_private_pod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get refs
      run: echo "${{ GITHUB_REF }}"
    
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      
    - name: check tag correctness
      run: echo "${{ env.TAG }}"
      
    - name: check removing first char
      run: cut -c 2- "${{ env.TAG }}"
